name: Build Android APK (Buildozer - native Ubuntu)

on:
  push:
    branches: [ "**" ]        # rulează pe orice branch
  workflow_dispatch:           # permite Run workflow manual din Actions

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-v1-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Buildozer/.buildozer
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            ~/.buildozer
          key: ${{ runner.os }}-buildozer-v1-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: System deps (native)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip git libffi-dev libssl-dev \
            liblzo2-dev liblzma-dev zlib1g-dev \
            autoconf automake libtool pkg-config \
            libjpeg-dev libfreetype6-dev

      - name: Install Buildozer & tools
        run: |
          python -m pip install --upgrade pip wheel
          pip install "setuptools==69.5.1"
          pip install "Cython==0.29.36" "buildozer==1.5.0" "python-for-android==2024.1.21"
          python -m buildozer --version
          python - << 'PY'
import importlib
m = importlib.import_module("p4a")
print("python-for-android:", getattr(m, "__version__", "unknown"))
PY

      - name: Set up JDK 17 (required by AGP/Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Force NDK r25b for p4a
        run: |
          echo "ANDROID_NDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

      - name: Tweak buildozer.spec (API 33, verbose, AndroidX)
        run: |
          test -f buildozer.spec
          # log_level = 2
          sed -i 's/^#\? *log_level *= *.*/log_level = 2/' buildozer.spec
          # enforce android.api = 33
          if grep -qi '^android\.api' buildozer.spec; then
