name: Build Android APK (Buildozer - native Ubuntu)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip python3 python3-pip python3-venv \
            openjdk-17-jdk libffi-dev libssl-dev \
            libncurses5:i386 libstdc++6:i386 zlib1g:i386 libc6:i386

      - name: Setup Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install "cython<3" buildozer

      - name: Show versions
        run: |
          source .venv/bin/activate
          python --version
          buildozer --version

      - name: Build APK (debug)
        run: |
          source .venv/bin/activate
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: prazzers-score-apk
          path: bin/*.apk
