name: Build Android APK (Buildozer - Docker)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Buildozer version
        run: buildozer --version

      - name: Build APK (debug)
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: prazzers-score-apk
          path: bin/*.apk
