name: Build Android APK (Buildozer)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install system deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip openjdk-11-jdk python3 python3-pip \
            libffi-dev libssl-dev libncurses5:i386 libstdc++6:i386 zlib1g:i386 libc6:i386

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip install cython buildozer

      - name: Build APK (debug)
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: prazzers-score-apk
          path: bin/*.apk
